apiVersion: v1
kind: ConfigMap
metadata:
     name: 12-maria-sulca-config
     namespace: mariasulca
data:
     SPRING_PROFILES_ACTIVE: "dev"
     SPRING_APPLICATION_NAME: "vg-ms-users-management"
     SERVER_PORT: "9083"
     VITE_API_USERS_URL: "http://maria-sulca-users-service:9083"
     VITE_API_BASE_URL: "http://maria-sulca-users-service:9083/api/v1"
